// Command docgen renders the Ren runtime reference (docs/runtime.md) from the
// structured documentation that the builtins and modules packages expose. It is
// invoked by `go generate ./...`; do not edit the generated file by hand.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/deepnoodle-ai/risor/v2/pkg/object"

	"github.com/foohq/ren/builtins"
	"github.com/foohq/ren/modules"
)

func main() {
	out := flag.String("out", "docs/runtime.md", "output file")
	flag.Parse()

	var b bytes.Buffer
	writeHeader(&b)
	writeSchemes(&b)
	writeBuiltins(&b, builtins.Docs())
	writeModules(&b, modules.Docs())

	if err := os.WriteFile(*out, b.Bytes(), 0o644); err != nil {
		log.Fatalf("docgen: %v", err)
	}
	fmt.Printf("docgen: wrote %s\n", *out)
}

func writeHeader(b *bytes.Buffer) {
	b.WriteString("# Ren runtime reference\n\n")
	b.WriteString("<!-- Code generated by internal/tools/docgen; DO NOT EDIT. -->\n")
	b.WriteString("<!-- Run `go generate ./...` to regenerate. -->\n\n")
	b.WriteString("This is the environment a packaged Risor script runs in: the global ")
	b.WriteString("builtins available without an import, and the modules importable via ")
	b.WriteString("the `builtin://` scheme.\n\n")
}

func writeSchemes(b *bytes.Buffer) {
	b.WriteString("## Imports\n\n")
	b.WriteString("Scripts load code with the `import` builtin, resolved by URL scheme:\n\n")
	b.WriteString("| Form | Resolves to |\n|---|---|\n")
	b.WriteString("| `import(\"builtin://name\")` | A built-in module registered with the runtime (see below). |\n")
	b.WriteString("| `import(\"path/to/mod\")` | A compiled module from the package, relative to the package root. |\n")
	b.WriteString("| `import(\"package://path/to/mod\")` | The explicit form of a bare package path. |\n\n")
}

func writeBuiltins(b *bytes.Buffer, specs []object.FuncSpec) {
	b.WriteString("## Global builtins\n\n")
	b.WriteString("Available to every script without an import.\n\n")
	writeSpecTable(b, specs)
}

func writeModules(b *bytes.Buffer, mods []modules.ModuleDocs) {
	b.WriteString("## Modules\n\n")
	b.WriteString("Import with `import(\"builtin://<name>\")`, for example ")
	b.WriteString("`os := import(\"builtin://os\")`.\n\n")
	for _, m := range mods {
		fmt.Fprintf(b, "### `%s`\n\n", m.Name)
		if m.Doc != "" {
			b.WriteString(m.Doc)
			b.WriteString("\n\n")
		}
		writeSpecTable(b, m.Funcs)
	}
}

func writeSpecTable(b *bytes.Buffer, specs []object.FuncSpec) {
	sorted := make([]object.FuncSpec, len(specs))
	copy(sorted, specs)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	b.WriteString("| Signature | Returns | Description |\n|---|---|---|\n")
	for _, s := range sorted {
		fmt.Fprintf(b, "| `%s` | %s | %s |\n",
			signature(s), cell(s.Returns), description(s))
	}
	b.WriteString("\n")
}

// signature renders a call signature such as `join(elem...)` or `getpid()`.
func signature(s object.FuncSpec) string {
	return fmt.Sprintf("%s(%s)", s.Name, strings.Join(s.Args, ", "))
}

// description combines the doc string with an optional example.
func description(s object.FuncSpec) string {
	doc := cell(s.Doc)
	if s.Example != "" {
		doc += fmt.Sprintf("<br>Example: `%s`", strings.ReplaceAll(s.Example, "|", "\\|"))
	}
	return doc
}

// cell escapes a value for inclusion in a Markdown table cell.
func cell(s string) string {
	if s == "" {
		return "—"
	}
	return strings.ReplaceAll(s, "|", "\\|")
}
